[package]
name = "livebucket"
version = "0.1.0"
edition = "2021"

[dependencies]
sled = "*"
websocket = "*"
serde = {version = "*", features = ["derive"]}
serde_json = "*"
uuid = {version = "*", features = ["v4"]}
crossbeam = "*"